### ISSUE TITLE
Is there any issue for Compute Engine Activity badges ?

### ISSUE THREAD

**Issue by ejouvin** [QualInsight/qualinsight-plugins-sonarqube-badges#65] opened 2017-01-05 00:48 UTC
Hello.

On my instance, it always a badge with not found.
On the wiki, it is the same.

Or I missed something ?

In fact, I tryed the rest API on sonarqube with something like : 
<ROOT_URL>/sonar/api/ce/activity?q=<PROJECT_KEY>

and I got the answer :
{"errors":[{"msg":"Requires administration permission"}]}

Even if I am logged as administrator.

So In fact, this is explained in your known restrictions ?

Regards

**Comment by ejouvin** [comment] 2017-01-05 12:09
Confirmed, this is a security "issue" from SonarQube, I am using 6.2
May be not the case with earlier version, but this metrics required the administration permit.

So it can not be used.

**Comment by pawlakm** [comment] 2017-01-09 22:21
Hi, 

Indeed, this is a SQ limitation related to #15. I really don't understand their logic, but I can't do anything about it (well something could be probably done using aspects, but in my humble opinion the issue is on SQ's side: they should rather allow administrators to explicitly enable some webservices to access secured webservices)

Anyway, there is a way to circumvent this issue if you're using your own SQ instance and can put a reverse proxy in front of it (for instance a HAProxy instance). Here are the steps to achieve this:

1. You need to create a ``<securitytoken>`` having the rights to call the webservices that are secured.
2. configure your reverse proxy to rewrite urls as follows (pseudocode): ``https://yourhost/sqbadges/*`` should be rewritten to ``https://<securitytoken>@yourhost/sonar/api/badges/*`` (in fact you need to have HAProxy add a basic security header). This will allow you to add required credentials under the hood when calling the ``https://yourhost/sqbadges/*`` url and thus display all badges (without showing these credentials). Note: do not forget to keep all parameters.

Tell me if it is a viable workaround for you.

Kind regards,

Michel

**Comment by ejouvin** [comment] 2017-01-09 22:39
Oh ok.

Not so "simple", but really beacause of the logic from SonarQube.
Not sure I will be agree to make this trick. I am going to thing about that (but not soon) and let you know.
I did close the issue because it was not a big issue for me.

Will let you know

**Comment by pawlakm** [comment] 2017-01-09 23:11
ok I'm closing the issue then.

**Closed as completed by pawlakm** 2017-01-09 23:11 UTC
Labels: question
